version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    container_name: app
    hostname: app
    volumes:
      - socket:/tmp

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - socket:/tmp

volumes:
  socket: